---
title: "About Me"
---

Name: Chaitanya Shekar

Net ID: cs2046

Hello everyone! My name is Chaitanya Shekar pursuing my masters degree in Data Science and Analytics at Georgetown University. I graduated with a bachelor's degree with a major in statistics, mathematics, and economics. During the intensive programming component of my master's degree, I'm learning skills and techniques to deal with unique challenges in complex algorithms and scientific problems. My DSAN goals involve strengthening my machine learning and deep learning understanding and programming skills.

As I take a quick look about, I see that the utilization of big data for business applications, establishing marketing trends, and forecasting consumer behavior has skyrocketed, and as a direct consequence of this, the demand for both business and data analysts has also considerably increased. I want to deepen my understanding of data science and statistics as well as have a better handle on the intricacies that are present in both areas of study. My high school placed a significant emphasis on mathematics and science, which kindled my interest in data and motivated me to pursue a degree in statistics while I was enrolled in my university studies. As a consequence of this, I aimed my qualifications in the right direction and worked on developing my analytical skills in order to acquire a deeper comprehension of the influence that data can wield.

I consider myself to be an ambitious person who has the long-term goal of working in the field of data science at some point in the not-too-distant future. I would like to continue developing my talents in this area. In addition to completing the requirements for a conventional graduate degree, I also earned certificates in data science and analysis, machine learning, neural networks, deep learning, programming in Python and R, and all these subjects. Because I have such a great interest in data sciences, I decided to carry this out. To estimate who would emerge triumphant from a game of roulette based on statistical probability and game theory as the underlying concepts, I constructed a model-based project for the inter-collegiate Statistics Festival. During the time that I was an undergraduate student, I took part in a project in the field of data science that concentrated primarily on statistical principles. The study focused on cardiovascular health and the factors that are related with increased risk of cardiovascular disease.

Following the completion of my undergraduate degree, I obtained an internship with Feedback Business Consulting Services Pvt, Bangalore, in the role of research analyst. As part of my responsibilities, I was responsible for managing the data gathering for the Patent Operations B2B benchmark research as well as performing analysis.

After giving my current skill set and the demand for innovative analyst’s considerable consideration, I've come to the conclusion that I want to initiate the process of converting myself into a global citizen who is capable of thriving in high-pressure work environments. This course will provide me with the right steppingstone to enable me to enter the field of sophisticated technology and play a leadership role in the investigation and development of breakthroughs of this kind. This class will also prepare me to enter the field of sophisticated technology. Because of the meticulous study, analysis, and presentation of needs that the program provides, I am in a position where I can provide ideas and provide professional advice. I am extremely confident that it will assist me in applying the skills by undertaking projects and paving the path for ground-breaking research and development; furthermore, the emphasis on real-world skills, such as problem-solving, legal, ethical, and professional framework throughout the course that would give a holistic view. I am extremely confident that it will assist me in applying the skills by undertaking projects and paving the path for ground-breaking research and development. My head is spinning at the amazing amount of data and breadth that is necessary because I am detail-oriented, enjoys working with a variety of data, and appreciates performing analysis. The development of the capabilities and skills essential to prosper in the industry while also being able to adjust to the continuous changes that are taking place in that sector is the purpose of the program. In addition to my academic interests now, at a time when the global information technology industry is on the edge of a major technological transition, the data sciences are crucial to our attempts to explore the next frontier.

I am quite proud of my academic achievements, but as a person, I am also aware of the advantages I have enjoyed in life, and I want to help close the gaps by making positive contributions toward creating a more equitable world. It motivated me to get involved in actions for social causes, such as becoming an active member of the core committee of Amnesty International. was an event that left me feeling really fulfilled and got me thinking about how I could put my skills to use in the service of social improvement. When I think back on my path, I realize that it was at that point that I first became aware of the applications of data sciences in a variety of fields, including but not limited to business, artificial intelligence, healthcare, sustainability, and climate change. During that time, I participated in several different events and campaigns in which I pushed for human rights, LGBTQ rights, and the rights of other underrepresented groups in our society. As part of my efforts to further the cause, I went to Home of Hope, a shelter for the disadvantaged, and while there, I became aware of socioeconomic and structural disparities. Not only that, but I also took part in efforts to raise general awareness about cancer and the silent march for AIDS. It was something I desired to investigate, and I dove headfirst into the data.

In addition to pursuing a career in academia, one of my passions is traveling and learning about new countries and ways of life. In addition, a significant reason for me to get involved in the fight against climate change and global warming is to promote sustainable living practices in all aspects of human endeavor.

\
